% describe the schema of sources and views
%s: drones_cur_state(UAV_ID, LOC_NODE_ID,VIEW_RANGE,LOAD_NUM,CUR_ELECTRICITY,FLYING_STATE,
                     CUR_PATH_LENGTH,CUR_RESOURCE_COST,CUR_TIMESTAMP).
%s: drones_config(UAV_ID,FLEET_ID,SENSE_RANGE,LOAD_CAP,MAX_ELECTRICITY,CHARGE_EFFICIENCY).
%s: nodes_config(NODE_ID,POS_X,POS_Y,VISIT_CAP).
%s: cur_processes(REQ_UUID,PROC_ID,UAV_ID,R_W,TIME_INFO).
%v: drone_self_info(UAV_ID, LOC_NODE_ID,VIEW_RANGE,LOAD_NUM,CUR_ELECTRICITY,FLYING_STATE,
                     CUR_PATH_LENGTH,CUR_RESOURCE_COST,
                     FLEET_ID,SENSE_RANGE,LOAD_CAP,MAX_ELECTRICITY,CHARGE_EFFICIENCY,POS_X,POS_Y).

% rules for insertion and deletion from drones_cur_state
+drones_cur_state(UID,NID,VR,LN,CE,FS,L,RC,T)
    :-  drone_self_info(UID,NID,VR,LN,CE,FS,L,RC,FID,SR,LC,ME,CHE,PX,PY),
        drones_config(UID,FID,SR,LC,ME,CHE),
        drones_cur_state(UID,_,_,_,_,_,_,_,T),
        cur_processes(RID,PID,UID,_,_), PID=0,
        not drones_cur_state(UID,NID,VR,LN,CE,FS,L,RC,T).
-drones_cur_state(UID,NID,VR,LN,CE,FS,L,RC,T)
    :-  drones_cur_state(UID,NID,VR,LN,CE,FS,L,RC,T),
        drones_config(UID,FID,SR,LC,ME,CHE), nodes_config(NID,PX,PY,_),
        cur_processes(RID,PID,UID,_,_), PID=0,
        not drone_self_info(UID,NID,VR,LN,CE,FS,L,RC,FID,SR,LC,ME,CHE,PX,PY).
