%s: grid_nodes(NODE_ID,VISIT_COUNT,VISITED,VICTIMS_NUM,NEED_RESCUE,NODE_TYPE).
%s: grid_edges(FROM_ID,TO_ID,EDGE_ID,DISTANCE).
%s: cur_processes(REQ_UUID,PROC_ID,UAV_ID,R_W,TIME_INFO).
%s: drones_cur_state(UAV_ID, LOC_NODE_ID,VIEW_RANGE,LOAD_NUM,CUR_ELECTRICITY,FLYING_STATE,
                     CUR_PATH_LENGTH,CUR_RESOURCE_COST,CUR_TIMESTAMP).
%s: nodes_config(NODE_ID,POS_X,POS_Y,VISIT_CAP).
%v: drone_local_edges(UAV_ID,FROM_ID,TO_ID,EDGE_ID,DISTANCE).

tmp_pos(UID,UPX,UPY,VR)
    :- drones_cur_state(UID,NID,VR,_,_,_,_,_,_),nodes_config(NID,UPX,UPY,_),
    cur_processes(RID,PID,UID,_,_), PID=0.
tmp_range(UID,NID,PX,PY)
    :- grid_nodes(NID,_,_,_,_,_),nodes_config(NID,PX,PY,_),tmp_pos(UID,UPX,UPY,VR),
    (UPX-PX)*(UPX-PX)+(UPY-PY)*(UPY-PY)<=VR*VR.
tmp_edges(UID,FID,TID,EID,DIS)
    :- grid_edges(FID,TID,EID,DIS), tmp_range(UID,NID,PX,PY), NID=FID.
tmp_local_edges(UID,FID,TID,EID,DIS)
    :- drone_local_edges(UID,FID,TID,EID,DIS), tmp_range(UID,NID,PX,PY), NID=FID.

-grid_edges(FID,TID,EID,DIS)
    :- grid_edges(FID,TID,EID,DIS), tmp_edges(UID,FID,TID,EID,DIS),
    tmp_range(UID,NID,PX,PY), NID=TID,
    not drone_local_edges(UID,FID,TID,EID,DIS).
+grid_edges(FID,TID,EID,DIS)
    :- drone_local_edges(UID,FID,TID,EID,DIS), tmp_local_edges(UID,FID,TID,EID,DIS),
    tmp_range(UID,NID,PX,PY), NID=TID,
    not grid_edges(FID,TID,EID,DIS).